[package]
name = "core-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfd = {workspace = true}
rustc-hash = {workspace = true}
thiserror = {workspace = true}
ropey = {workspace = true}
highlighter = {path = "../highlighter"}
buffer = {path = "../buffer"}
mlua = { version = "0.9.6", features = ["lua54", "vendored", "unstable"] }
dirs = "5.0"
toml = "0.8.14"

[dev-dependencies]
pretty_assertions = {workspace = true}
